### ISSUE TITLE
Не выставляет оценки

### ISSUE THREAD

**Issue by f242** [REDNBLACK/J-Kinopoisk2IMDB#1]
винда 8.1 х64 запущена на варе
поставил последнюю яву и лису
запустил .ехе последний, открыл в нём эксель со своими оценками
в лисе открыл имдб, авторизовался, нашёл куку id и скопировал промотав вправо ибо параметр длинный
вставил куку из буфера, списочки не выбирал ибо их нету и нужно только выставление оценок, такой режим и выбрал - без списков, просто оценки
нажал запустить
кнопка отобразила что идёт процесс
и всё, может секунд 15 была какая-то активность и всё, больше ничего не происходит, хоть бы какая консоль открывалась где видно что что-то там происходит

**Comment by REDNBLACK** [comment]
Консоли нет, есть лог.
Зайдите в Пользователи/Имя пользователя/K2IDB/logs/K2IDB.log
откройте и запостите сюда его содержимое.

**Comment by REDNBLACK** [comment]
И да, прогресс бар (тот что слева от кнопки запустить), заполнялся или ничего не происходило?

**Comment by f242** [comment]
прогрессбар остаётся пустым, только кнопка запуска сменяется на "в процессе"
вот лог
[K2IDB.txt](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/211932/K2IDB.txt)

на имдб ни одной оценки так и не появилось

**Comment by REDNBLACK** [comment]
2016-04-10 22:18:55,694 INFO  AbstractMovieHandler [SetRatingHandler.java:28] Setting rating of movie: Movie{id=2, title=I Smile Back, year=2015, imdb_id=tt3640682}
2016-04-10 22:18:55,695 INFO  AbstractMovieHandler [SetRatingHandler.java:36] Movie doesn't have rating!

Вот и ваша проблема, список с кинопоиска был экспортирован без оценок.
Откройте в блокноте и проверьте сами если не верите мне, у каждого фильма десятый столбец сверху должен иметь цифру от 0 до 10

**Comment by REDNBLACK** [comment]
Либо скиньте xls файл сюда, если уверены что ошибка в программе или лень смотреть файл.

**Comment by f242** [comment]
[votes.zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/211938/votes.zip)

**Comment by REDNBLACK** [comment]
Да, ошибка в программе, починю в следующей версии. 
Попробуйте экспортировать способом через 

> Мой кинопоиск -> Фильмы -> Список с фильмами -> Экспорт в MS Excell

**Comment by f242** [comment]
а у меня и на кинопоиске списков нет, там я могу экспортнуть только "буду смотреть" и "примечания", так что буду ждать новую версию, спасибо за труды

**Comment by REDNBLACK** [comment]
Исправил, можете перекачать и пробовать.
На всякий случай в Дополнительных настройках, поставьте галочку `Чистый запуск`

**Comment by f242** [comment]
появилось несколько оценок из ~2500, и тишина, прогрессбар по прежнему неактивен, вот лог
[K2IDB.txt](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/212074/K2IDB.txt)

**Comment by REDNBLACK** [comment]
Он не не активен, скорее не может пока отрисовать прогресс на такое большое количество оценок. 
После этой строки ничего не появилось в логе? 
2016-04-11 02:12:56,094 INFO  AbstractMovieHandler [ParseIDHandler.java:33] Preparing movie Movie{id=16, title=Crystal Fairy & the Magical Cactus and 2012, year=2013, rating=4}

**Comment by REDNBLACK** [comment]
А вобще спасибо за идею, сделать чтоб отображало также в прогресс баре текущий шаг и общее количество импортируемых фильмов.

**Comment by f242** [comment]
сделал чистый запуск, ждал 40 минут, всё те же 14 оценок, вот лог
[K2IDB.txt](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/212422/K2IDB.txt)

**Comment by REDNBLACK** [comment]
<img width="712" alt="2016-04-11 12 53 10" src="https://cloud.githubusercontent.com/assets/1498939/14423419/6d4c34fa-ffe4-11e5-9091-db9d7265f6e3.png">

Ага у меня тоже на 14 ровно зависло с вашего списка... Буду смотреть что не так

**Comment by REDNBLACK** [comment]
Нашел ошибку. В следующем релизе сегодня будет фикс. Спасибо большое за тесты

**Comment by REDNBLACK** [comment]
Удалось починить в новом релизе, проверьте плиз:

<img width="712" alt="2016-04-11 13 31 24" src="https://cloud.githubusercontent.com/assets/1498939/14424661/fe9d3868-ffea-11e5-87d4-e421bff13312.png">

**Comment by f242** [comment]
теперь .ехе не запускается, в диспетчере на секунду мелькает javaw.exe и всё

**Comment by REDNBLACK** [comment]
Удалите config.json в Пользователи/Имя пользователя/K2IDB.
Правда настройки нужно заново будет указать.
И да, чистый запуск не обязательно делать, для того же файла оно продолжит с нужного места.

**Comment by f242** [comment]
ура! процесс пошёл, перевалило за 100

**Comment by f242** [comment]
застряло на 109

**Comment by REDNBLACK** [comment]
Я с вашего файла смог импортировать 2346 оценок:
<img width="692" alt="2016-04-11 15 00 38" src="https://cloud.githubusercontent.com/assets/1498939/14426238/39079bf0-fff6-11e5-871d-68a9d93e9988.png">

**Comment by REDNBLACK** [comment]
А что в логах? Или уже прошло?

**Comment by f242** [comment]
нет, на 109 так и застопорилось
[K2IDB.txt](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/212872/K2IDB.txt)

**Comment by REDNBLACK** [comment]
Попробуйте закрыть и открыть снова программу. Странно, по логам все ок, должно было вылететь по таймауту.

**Comment by f242** [comment]
снова на 109 затык
делаю чистый запуск, просто выставить рейтинг

**Comment by REDNBLACK** [comment]
Файл с оценками у меня есть, и с него успешно импортировалось 2346 фильмов...
Так попробуйте следующее, а я тоже попробую:
1. Сотрите всю папку Пользователи/Имя пользователя/K2IDB
2. В настройках Для экспертов выставите log_level в debug.
3. Заново запустите, и пришлите лог.

**Comment by f242** [comment]
опять 109
[K2IDB.txt](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/212926/K2IDB.txt)

**Comment by REDNBLACK** [comment]
Да, у меня тоже... Уже смотрю что не так.

**Comment by REDNBLACK** [comment]
Фух... Поправил, проверил с вашим списком, пошло дальше 120.
Надеюсь больше ошибок не будет.
https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/0.9.5

**Comment by f242** [comment]
да, вроде работает, за 500 перевалило

**Comment by REDNBLACK** [comment]
Ну наконец-то :)

**Comment by f242** [comment]
кажется рано радоваться, где-то в районе 700 счётчик быстро накрутился до 1800 буквально за пару секунд, как только закончится выложу дебаглог

**Comment by f242** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/10371194/14429512/6fcd2532-0006-11e6-933b-220fa9c98956.png)

лог 
[K2IDB.zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/213088/K2IDB.zip)

**Comment by REDNBLACK** [comment]
Ну тут все просто, либо отошли от компа и он перешел в режим сна, соотвественно программа потеряла соединение с сетью, и после того как копмьютер вышел из сна - программа продолжила вхолостую не дожидаясь восстановления соединения.

Пока просто запустите заново, продолжит с последнего не импортированного фильма.

А вот в качестве решения, я могу сделать так, что пока запущена программа - компьютер не сможет спать.

**Comment by f242** [comment]
переход в спящий режим отключён, ок, попробую повторно стартануть

**Comment by f242** [comment]
повторно процесс продолжился, оставалось ~1200 фильмов и снова кажется на отметке в 530 счётчик резко ускорился, на этот раз дойдя до конца и вылетело окошко, что работа завершена с ошибками как в прошлый раз

**Comment by REDNBLACK** [comment]
Из-за чего то теряется соединение с сетью, либо с самим IMDB, либо у вас отваливается.

Ну еще раз попробуйте запустить, может хоть сейчас до конца сможет.

**Comment by REDNBLACK** [comment]
Добавил в новом билде ожидание возврата соединения. Эту тему я так понимаю можно закрывать, все прошло ок?

**Comment by f242** [comment]
да, всё ок
