### ISSUE TITLE
Поиск только по фильмам

### ISSUE THREAD

**Issue by ertyz** [REDNBLACK/J-Kinopoisk2IMDB#11]
Версия 1.1.1 ищет не только по фильмам, но и по видеоиграм и прочему, чего на кинопоиске в принципе нет.

Например на фильм "Обитель зла (Resident Evil) (2002)" программа нашла и проставила оценку какой-то игре: http://www.imdb.com/title/tt0302327/

А мультсериал "Наруто" как http://www.imdb.com/title/tt0424302/

**Comment by REDNBLACK** [comment]
На самом деле данный функционал (поиск только по фильмам и сериалам) есть. Странно что не сработало.

Мне необходим ваш конфиг (config.json), лог (K2IDB.log) и (желательно) список использовавшийся для импорта (*.xls).
Конфиг и лог лежат в Пользователи/Имя пользователя/K2IDB/

**Comment by ertyz** [comment]
Я снял галочку "тип фильма с полным совпадением". Возможно произошло из-за этого. Просто не хотел сравнивать жанры, но уж видеоигра, это какой-то совсем "отдельный" жанр.

**Comment by REDNBLACK** [comment]
Это не жанры, это тип фильма :)

> Тип фильма с полным совпадением - индентичное сравнение типов фильмов (обычный/сериал/документальный/короткометражка)

Да, думаю стоит исключить все кроме типов относящихся к фильмам, а так да, ошибки никакой нет, закрываю.
