### ISSUE TITLE
Как обновить разницу оценок?

### ISSUE THREAD

**Issue by systems-rebooter** [REDNBLACK/J-Kinopoisk2IMDB#15]
Спасибо за востребованную прогу! 

Подскажите как правильно обновить разницу оценок просмотреных фильмов? 

Пробовал удалить из xls уже добавленые оценки - kinopoisk2imdb говорит что импортнула 0 фильмов (хотя должна около 40). Если дать неизмененный файл-экспорт с кинопоиска - прога обрабатывает все 1300 фильмов при снятой галочке "Чистый запуск" по новой.

**Comment by REDNBLACK** [comment]
Программа смотрит на хэшкод .xls файла, то есть при его изменении она будет считать, что это другой файл, и будет пытаться импортировать по новой. 
Вы можете заново импортировать поверх старых оценок, оценки спокойно перезаписываются. Могут возникнуть проблемы с дублями, лишь при добавлении в список.

**Comment by systems-rebooter** [comment]
Спасибо! Тоесть, разницу сейчас имортнуть никак не получиться, верно?

**Comment by REDNBLACK** [comment]
Да, верно

**Comment by systems-rebooter** [comment]
Eсли удастся прикрутить локальную базу AucT-a, это частично решит проблему. 

Покамись нашел такой выход:

`sed '/03.10.2016/q' kinopoisk.ru-votess.xls > kinopoisk.ru-votesss.xls`
_имортирует оценки, начиная с 3 октября 2016_

<img width="602" alt="screen shot 2016-10-05 at 10 42 17" src="https://cloud.githubusercontent.com/assets/8888190/19105138/1dfb030a-8ae9-11e6-85d4-027e8392875e.png">

Кто ж мог подумать что кинопоисковый xls это raw html :]

Думаю, можно закрывать.
