### ISSUE TITLE
Can't add movie to watchlist, error status code: 403

### ISSUE THREAD

**Issue by kybarg** [REDNBLACK/J-Kinopoisk2IMDB#16]

**Comment by REDNBLACK** [comment]
Скорее всего строка авторизации не указана или указана неправильно.

**Comment by kybarg** [comment]
Нет я подключаюсь и оно парсит, но не может добавить.

**Comment by REDNBLACK** [comment]
Пришлите config.json и K2IDB.log из папки Пользователи/Имя пользователя/K2IDB, попробую посмотреть в чем дело
