### ISSUE TITLE
Ошибка "Can't change movie rating"

### ISSUE THREAD

**Issue by Funkadelik** [REDNBLACK/J-Kinopoisk2IMDB#18]
Здравствуйте
Выдает такую ошибку
![error 1](https://cloud.githubusercontent.com/assets/25404805/22398060/2cddb1d4-e588-11e6-97fd-2f8fa92a6c74.png)
Строку авторизации IMDB указал. Файрвол на всякий случай отключал.
В файле лога пишет такое 

> 2017-01-28 15:31:17,684 INFO  MovieHandler [SaveChangesHandler.java:27] Changes were successfully saved to storage
> 2017-01-28 15:31:17,831 INFO  MovieHandler [ConnectionCheckHandler.java:41] IMDB url is successfully reached!
> 2017-01-28 15:31:17,832 INFO  MovieHandler [ParseIDHandler.java:35] Preparing movie Movie(title=Ouija: Origin of Evil, year=2016, type=MOVIE, rating=7, imdbId=null)
> 2017-01-28 15:31:18,009 INFO  MovieHandler [ParseIDHandler.java:48] Movie IMDB id successfully found: tt4361050
> 2017-01-28 15:31:18,009 INFO  MovieHandler [SetRatingHandler.java:33] Setting rating of movie: Movie(title=Ouija: Origin of Evil, year=2016, type=MOVIE, rating=7, imdbId=tt4361050)
> 2017-01-28 15:31:19,438 INFO  MovieHandler [SetRatingHandler.java:70] Error setting rating of movie: {}
> java.io.IOException: Movie authorisation string is empty!
> 	at org.f0w.k2i.core.handler.SetRatingHandler.handleMovie(SetRatingHandler.java:55)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:72)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.Client.run(Client.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)

Вот что в файле config 

> {"auth":"_**тут моя строка авторизации IMDB**_","comparators":["YEAR_DEVIATION","TYPE_EQUALS","TITLE_SMART"],"db":{"additional":{"hibernate.dialect":"org.hibernate.dialect.H2Dialect","hibernate.hbm2ddl.auto":"update"},"driver":"org.h2.Driver","password":"root","url":"jdbc:h2:~/K2IDB/db/K2IDB;TRACE_LEVEL_FILE=4","user":"root"},"document_source_types":["XML","JSON"],"list":"","log_level":"info","mode":"SET_RATING","timeout":3000,"user_agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36","year_deviation":1}

**Comment by REDNBLACK** [comment]
IMDB что-то поменяли на сайте видимо, надо глянуть

**Comment by goldeneagle1** [comment]
У меня похожая проблема: 
Good Will Hunting(1997):
Can't change movie rating, error status code: 403
Can't add movie to watchlist, error status code: 403


И так для всех фильмов, похоже. В итоге пишет, что были обработаны 0 фильмов из общего количества.
