### ISSUE TITLE
Не запускается.

### ISSUE THREAD

**Issue by stepan0809** [REDNBLACK/J-Kinopoisk2IMDB#19]
Нажимаешь кнопку "Запустить" он покрутит колёсико возле мышки и всё. Никакого действия.

**Comment by REDNBLACK** [comment]
Какая ОС? Версия Java?
Пришлите config.json и K2IDB.log из папки Пользователи/Имя пользователя/K2IDB, по такому описанию ничего не ясно.

**Comment by stepan0809** [comment]
Странно, но я никак не могу прикрепить ни один тип файлов. При том что они указаны тут. Можно по почте сбросить?

**Comment by stepan0809** [comment]
https://cloud.mail.ru/public/7Xhp/bsGA3XfFx Загрузил в облако Mail.ru вирусов нет.

**Comment by REDNBLACK** [comment]
А попробуйте удалить всю папку K2IDB и запустить заново, предварительно убив/закрыв все процессы java.
Очень странно, файл базы данных блокируется.

**Comment by stepan0809** [comment]
![image](https://cloud.githubusercontent.com/assets/25491222/22560403/29bbadfa-e97d-11e6-82af-d0d5cdb753ff.png)

**Comment by stepan0809** [comment]
https://cloud.mail.ru/public/JC7P/vS2AM5QC7

**Comment by stepan0809** [comment]
Так что, никакой помощи не будет? Уже 11 дней прошло.

**Comment by REDNBLACK** [comment]
А откуда взят файл с оценками? Экспортирован с кинопоиска? Если да, то у них сильно поменялась структура файлов, нужно переделывать программу. 
Больше похоже на файл созданный вручную.

**Comment by stepan0809** [comment]
Да, файл взят с кинопоиска. Ничего не исправлено и не отредактировано.

**Comment by REDNBLACK** [comment]
К сожалению нет времени на заработку, пока ничем не могу помочь.
Добавлю в описание пометку, что с новыми файлами не работает.

**Comment by shishkoam** [comment]
А есть пример старого формата?

**Comment by REDNBLACK** [comment]
@shishkoam вот
[kinopoisk.ru-test.xls.zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/1008330/kinopoisk.ru-test.xls.zip)

**Comment by REDNBLACK** [comment]
Мне тут сообщили, что кинопоиск вернул старый формат экспортированных файлов. Так что вроде должно вновь работать. Пусть для вас уже это и не актуально.

**Comment by wapec** [comment]
![screenshot from 2018-01-01 19 05 46](https://user-images.githubusercontent.com/15906319/34469410-e2e09e80-ef26-11e7-9f5f-dd6e2a5583ce.png)
os: solus 3
java: openjdk version "1.8.0_172-solus"
OpenJDK Runtime Environment (build 1.8.0_172-solus-b00)
OpenJDK 64-Bit Server VM (build 25.172-b00, mixed mode)
