### ISSUE TITLE
Добавить в ошибки данные + Перенос в Watchlist

### ISSUE THREAD

**Issue by dpashutskii** [REDNBLACK/J-Kinopoisk2IMDB#20]
1. После импорта оценок выдается таблица со списком фильмов которые не удалось замапить, скорее всего если их немного то это будет делаться вручную, хорошо было бы в ошибки вывести данные которые переносили (например имя фильма и оценку), чтобы сразу можно было внести данные вручную.
2. Очень не хватает функции переноса фильмов в Watchlist, или я просто не нашел?

**Comment by REDNBLACK** [comment]
2. В watchlist тоже возможно добавить. Нужно указать его id, как id списка для добавления

**Comment by REDNBLACK** [comment]
1. Вроде же есть имя фильма в том окне? Оценку постараюсь добавить.

**Comment by dpashutskii** [comment]
1. Ну да я именно про оценку, иначе приходилось копировать название смотреть оценку и вручную проставлять. Спасибо!
2. По поводу id так же с начала подумал, но где его id? В командной строке такое: 
![image](https://user-images.githubusercontent.com/13599412/28493559-7720574c-6f21-11e7-8a53-179b4d5ef5f7.png)

**Comment by extempl** [comment]
`Watchlist` как список для импорта был добавлен несколько ранее.

Вывод оценок в результат на данный момент не актуально, посколько через приложение импорт оценок в принципе не работает. Работает через букмарклет (версия 1.2.4)
