### ISSUE TITLE
Matching movie not found, Can't change movie rating, IMDB ID is not set

### ISSUE THREAD

**Issue by ChildrenofkoRn** [REDNBLACK/J-Kinopoisk2IMDB#22]
При попытке отправить на IMDB получаю ошибки:
(Пробовал перелогиниться, чтобы получить другой ID, тоже самое)
Win 7 x64
```
Law Abiding Citizen(2009):
Matching movie not found
Can't change movie rating, IMDB ID is not set
Can't add movie to watchlist, IMDB ID is not set


Terminator 2: Judgment Day(1991):
Matching movie not found
Can't change movie rating, IMDB ID is not set
Can't add movie to watchlist, IMDB ID is not set


Blade Runner 2049(2017):
HTTP error fetching URL

```

> 2018-02-01 22:55:55,629 INFO  MovieHandler [ConnectionCheckHandler.java:41] IMDB url is successfully reached!
> 2018-02-01 22:55:55,631 INFO  MovieHandler [ParseIDHandler.java:35] Preparing movie Movie(title=Law Abiding Citizen, year=2009, type=MOVIE, rating=8, imdbId=null)
> 2018-02-01 22:55:57,385 INFO  MovieHandler [ParseIDHandler.java:50] Can't prepare movie: {}
> java.io.IOException: Matching movie not found
> 	at org.f0w.k2i.core.handler.ParseIDHandler.lambda$handleMovie$0(ParseIDHandler.java:44)
> 	at java.util.Optional.orElseThrow(Unknown Source)
> 	at org.f0w.k2i.core.handler.ParseIDHandler.handleMovie(ParseIDHandler.java:44)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:72)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.Client.run(Client.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-02-01 22:55:57,386 INFO  MovieHandler [SetRatingHandler.java:33] Setting rating of movie: Movie(title=Law Abiding Citizen, year=2009, type=MOVIE, rating=8, imdbId=null)
> 2018-02-01 22:55:57,386 INFO  MovieHandler [SetRatingHandler.java:70] Error setting rating of movie: {}
> java.io.IOException: Can't change movie rating, IMDB ID is not set
> 	at org.f0w.k2i.core.handler.SetRatingHandler.handleMovie(SetRatingHandler.java:37)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:72)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.Client.run(Client.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-02-01 22:55:57,386 INFO  MovieHandler [AddToWatchlistHandler.java:31] Adding movie to watchlist: Movie(title=Law Abiding Citizen, year=2009, type=MOVIE, rating=8, imdbId=null)
> 2018-02-01 22:55:57,386 INFO  MovieHandler [AddToWatchlistHandler.java:55] Error adding movie to watchlist: {}
> java.io.IOException: Can't add movie to watchlist, IMDB ID is not set
> 	at org.f0w.k2i.core.handler.AddToWatchlistHandler.handleMovie(AddToWatchlistHandler.java:35)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:72)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.Client.run(Client.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-02-01 22:55:57,388 INFO  MovieHandler [SaveChangesHandler.java:27] Changes were successfully saved to storage
> 2018-02-01 22:55:57,536 INFO  MovieHandler [ConnectionCheckHandler.java:41] IMDB url is successfully reached!
> 2018-02-01 22:55:57,536 INFO  MovieHandler [ParseIDHandler.java:35] Preparing movie Movie(title=Blade Runner 2049, year=2017, type=MOVIE, rating=8, imdbId=null)
> 2018-02-01 22:55:59,168 INFO  MovieHandler [ParseIDHandler.java:48] Movie IMDB id successfully found: tt7879362
> 2018-02-01 22:55:59,168 INFO  MovieHandler [SetRatingHandler.java:33] Setting rating of movie: Movie(title=Blade Runner 2049, year=2017, type=MOVIE, rating=8, imdbId=tt7879362)
> 2018-02-01 22:56:00,660 INFO  MovieHandler [SetRatingHandler.java:68] Movie rating was successfully set
> 2018-02-01 22:56:00,660 INFO  MovieHandler [AddToWatchlistHandler.java:31] Adding movie to watchlist: Movie(title=Blade Runner 2049, year=2017, type=MOVIE, rating=8, imdbId=tt7879362)
> 2018-02-01 22:56:00,984 INFO  MovieHandler [AddToWatchlistHandler.java:55] Error adding movie to watchlist: {}
> org.jsoup.HttpStatusException: HTTP error fetching URL
> 	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:537)
> 	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:493)
> 	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:205)
> 	at org.f0w.k2i.core.exchange.ExchangeObject.lambda$new$0(ExchangeObject.java:48)
> 	at org.f0w.k2i.core.util.exception.ExceptionUtils.lambda$rethrowSupplier$0(ExceptionUtils.java:37)
> 	at org.f0w.k2i.core.exchange.ExchangeObject.getResponse(ExchangeObject.java:61)
> 	at org.f0w.k2i.core.exchange.ExchangeObject.getProcessedResponse(ExchangeObject.java:69)
> 	at org.f0w.k2i.core.handler.AddToWatchlistHandler.handleMovie(AddToWatchlistHandler.java:45)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:72)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
> 	at org.f0w.k2i.core.Client.run(Client.java:77)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 2018-02-01 22:56:00,994 INFO  MovieHandler [SaveChangesHandler.java:27] Changes were successfully saved to storage

**Comment by REDNBLACK** [comment]
Вижу что какие-то проблемы с соединением. Программа достаточно прожорливая по ресурсам сети. Могу лишь посоветовать увеличить:

`timeout - Таймаут попытки соединения для каждого запроса; можете увеличить, если у вас, к примеру, плоблемы с интернетом. (По умолчанию) 3000`

**Comment by ChildrenofkoRn** [comment]
до imdb.com потерь нет:

> Статистика Ping для 52.94.237.74:
>     Пакетов: отправлено = 100, получено = 100, потеряно = 0
>     (0% потерь)
> Приблизительное время приема-передачи в мс:
>     Минимальное = 132мсек, Максимальное = 134 мсек, Среднее = 132 мсек

канал 70/70 mbits
из 137 на IMDB импортируется 55, при этом пишет, что все были с ошибками.
Таймаут увеличивал втрое, пробовал выставлять только XML.

А, ещё в сам список IMDB, ID которого использую, фильмы не добавляются, не знаю должны ли. Просто в профиль добавляются с оценкой и всё.

[debug.log](https://www.dropbox.com/s/zzsvc8a2wsz5n65/K2IDB_180206_1816.log?dl=0)

**Comment by marknorkin** [comment]
Также столкнулся с этой проблемой, увеличение таймаута, изменение настроек сравнения не помогло. Ни один фильм не удалось перенести из 500+. В логах тоже что и у @ChildrenofkoRn. Есть ли решение ?
