### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by KeshaFinkel** [REDNBLACK/J-Kinopoisk2IMDB#24]
Win 8.1 64bit
Java 8 update 171

Добавил файл, добавил куку, выставил режим только оценки и чистый запуск жму запустить ничего не происходит
[K2IDB.log](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2077815/K2IDB.log)

**Comment by REDNBLACK** [comment]
Не пробовали перезагрузить систему или убить процессы программы? По логу видно, что какой-то процесс блокирует доступ к базе данных программы.

**Comment by KeshaFinkel** [comment]
Пробовал не помогло, как я могу определить чем заблокирована база?

**Comment by REDNBLACK** [comment]
Попробуйте удалить папку с настройками программы и запустить эту версию:
https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v1.1.1

**Comment by REDNBLACK** [comment]
Кстати дело может быть в антивирусе

**Comment by MariaLovesGithub** [comment]
Тоже самое что в v1.1.1, что в v1.2 ничего не происходит после старта. Антивируса нет [K2IDB.log](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2181106/K2IDB.log)

**Comment by REDNBLACK** [comment]
@MariaLovesGithub ОС тоже Windows? И какая версия Java?

**Comment by MariaLovesGithub** [comment]
да Windows 7, Java Version 8 Update 171

**Comment by astronautzzz** [comment]
Win 10, Java Version 8 Update 181 все тоже самое что перчислено выше лог[](url)
[K2IDB.log](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2243196/K2IDB.log)
Сейчас приложения не запускаеться, не знаю почему.

**Comment by REDNBLACK** [comment]
@astronautzzz Не пробовали эту версию? https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v1.1.1

У меня нет Windows, чтобы проверить, на остальных ОС все замечательно. Нужно понять в какой версии приложения это проявляется.

**Comment by astronautzzz** [comment]
@REDNBLACK запустил приложение на Ubuntu 16.04 LTS, Java version 8 update 181. так же ничего не происходит после запуска.
[K2IDB.log](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2245767/K2IDB.log)
проверял на Windows версию v1.1.1 ничего не произошло, даже не запустилось

**Comment by REDNBLACK** [comment]
@astronautzzz перед запуском старой версии надо удалить папку с настройками программы всю

**Comment by extempl** [comment]
Пробуйте последнюю версию: https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v.1.2.3

Возможно у вас та же проблема, что и в #29.

Если всё так же - прикрепите последние логи.
