### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by docmikhail** [REDNBLACK/J-Kinopoisk2IMDB#25]
Версия 1.1.2. Все по инструкции.

Процесс шел несколько часов, по итогу сообщение: "Были обработаны 0 из 1655 фильмов".

Ошибки самые разные:

1.
Can't change movie rating, error status code: 403

2.
Read timed out
Can't change movie rating, IMDB ID is not set

3.
HTTP error fetching URL
Can't change movie rating, IMDB ID is not set

4.
Movie authorisation string is empty!

**Comment by REDNBLACK** [comment]
@docmikhail https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v1.1.1

Попробуйте удалить папку с настройками программы и запустить эту версию, очень похоже на плохое соединение с imdb

**Comment by docmikhail** [comment]
1. Удалил рабочие папки программы и саму программу
2. Скачал версию 1.1.1
3. Отключил антивирус
4. Запустил от имени админа
5. Заполнил все поля согласно инструкции.

Не помогло. Те же ошибки.

**Comment by docmikhail** [comment]
Пробовал повторить действия на виртуалке с чистой системой, где кроме Явы и вашего софта ничего не было. Результат такой же.

Что-то можно вообще сделать? Или про идею автоматического переноса оценок можно забыть?

**Comment by REDNBLACK** [comment]
скорее всего imdb что-то поменяли в своем процессе, к сожалению у меня нет времени чтобы починить.

**Comment by xtemp09** [comment]
Как жаль, что не работает. Яндекс уничтожает Кинопоиск, надо срочно бежать с корабля.

**Comment by yasujiroozu** [comment]
> скорее всего imdb что-то поменяли в своем процессе, к сожалению у меня нет времени чтобы починить.

Здравствуйте REDNBLACK. Вы совсем не собираетесь чинить программу?

**Comment by deityrox** [comment]
случайно не знаете,  как конвертнуть .xls от Кинопоиска в .csv IMDB? Потом его можно и импортировать в MovieLens, кому надо. (tag: convert )
Наверное я глупость спросил. Ведь необходим доступ к совмещенным базам обоих сайтов с перелинкованными названиями, либо напрямую выставление оценки через вашу прогу. То есть есть ли способ как-то в  оффлайне эти базы слинковать?
 Кому интересно, можете гуглить в эту сторону: https://spaceninja.com/2017/11/16/how-to-export-movie-ratings-from-netflix-and-import-into-imdb/ и https://github.com/tomzx/imdb-importer/issues

**Comment by extempl** [comment]
Из того, что я смог раскопать, так это то, что добавление фильмов в списки возможно починить, а голосование - нет. Для добавления фильмов используются новые авторизационные данные, а вот для голосования каждый раз генерируются новые ключи, видимо для противостоянию накрутке. Это только можно сэмулировать пользователя который будет ходить по страницам и кликать на звёздочки или только когда повится официальный API.

**Comment by yasujiroozu** [comment]
добрый вечер extempl. а вы сможете-возьмётесь починить списки?)

**Comment by extempl** [comment]
Исправил. Вроде бы работает. 
Pull request создан, пока не обновили тут, можно использовать версии моего форка: https://github.com/extempl/J-Kinopoisk2IMDB/releases/tag/v1.2.1

Если в логе есть ошибки 403 - значит где-то ошиблись в ключах конфигурации или они устарели. 
Рекомендую сразу включать OMDB (нужно получить ключ предварительно), повышает процент успешно импортированных фильмов.

**Comment by extempl** [comment]
Закрою этот реквест как исправленный, для исправления рейтинга создал новый #28. 
Пока нет уверенности что рейтинг будет работать.

**Comment by extempl** [comment]
Рейтинг работает через букмарклет (запуск из браузера). Смотрите последнюю версию и [README](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/blob/master/README.md)
