### ISSUE TITLE
не запускается

### ISSUE THREAD

**Issue by yasujiroozu** [REDNBLACK/J-Kinopoisk2IMDB#29]
спасибо extempl за оживление программы. 
после нажатия кнопки запустить, грузится секунду и далее ничего не происходит. удалял папку программы несколько раз и запускал по новой, установил последнюю java. win 7 64.
[K2IDB.log](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2888611/K2IDB.log)

**Comment by extempl** [comment]
Посмотрю. На всякий случай обновите свою Java до актуальной версии (8 update 201)

**Comment by extempl** [comment]
Проверил на Win8.1 со свежескачанной Java - всё в порядке. Похожую ошибку встречал, но не похоже что она влияет на результат. Скорее всего дело не в ней. 
Проверьте ещё раз что все ключи правильные (актуальные), проверьте на запросе с `watchlist` вместо id другого списка. 
Если так же - скиньте новый лог файл. 
Прикрепляю тестовый файл с одним фильмом
[kinopoisk.ru-Favorites-test.xls.zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2889359/kinopoisk.ru-Favorites-test.xls.zip)

**Comment by extempl** [comment]
С тестированием на одном файле есть нюанс, нужно после каждого успешного импорта удалять `K2IDB.mv.db` файл. Пока не решил эту проблему.

**Comment by yasujiroozu** [comment]
не могу понять в чем дело, ваш тестовый файл с одним фильмом переносит успешно, а мои никакие файлы не хочет, никакой реакции после нажатия кнопки "запустить". уже много раз проверил, разные папки с разными фильмами и K2IDB.mv.db удалял. вот тестовый файл с одним фильмом от меня [kinopoisk.ru-test (1).zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2890370/kinopoisk.ru-test.1.zip)
и лог
[K2IDB.log](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/2890379/K2IDB.log)

**Comment by extempl** [comment]
Дело в том, что поле "жанры" у нас используется для разделения на типы (документальный, короткометражка, фильм, сериал), а у вас в файле этого поля нет. Т.о. вам нужно переимпортировать список включив это поле, тогда всё будет работать.
Обновлю README.

**Comment by extempl** [comment]
Вижу, что сейчас так экспортируется по умолчанию.

**Comment by extempl** [comment]
@yasujiroozu  Пробуйте: https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v.1.2.3

**Comment by yasujiroozu** [comment]
ура, работает) спасибо большое)))
