### ISSUE TITLE
auth string (control key) length is less than or equal 10!

### ISSUE THREAD

**Issue by pdxLife** [REDNBLACK/J-Kinopoisk2IMDB#31]
Проверил все данные что я вводил, не помогает. 
Видимо что-то в авторизации не работает, но я не знаю на какую строку ругается программа

![imdb](https://user-images.githubusercontent.com/44197020/55674901-cc81ea80-58b2-11e9-83d1-1affd7b702ab.PNG)

**Comment by extempl** [comment]
Это видимо про "пара ключ-значение" - нужно заполнить. Правда оно длиной не 10, а меньше
