### ISSUE TITLE
Не переносит

### ISSUE THREAD

**Issue by M9SO** [REDNBLACK/J-Kinopoisk2IMDB#32]
Здравствуйте, всё сделал файл собственно итоговый получил ratings.json который, только при переносе на сам сайт, все фильмы без каких либо ошибок скипает. Ошибок в консоле не выдаёт, да вообще нечего там не выдаёт. Пытался разные фильмы, разные папки как и просто просмотр так и оценка. При формировании файла выдаёт  ошибку на некоторые позиции  "Can't add movie to watchlist, error status code: 403".

**Comment by extempl** [comment]
Уточните, не работает вообще ничего? Ratings.json и часть на сайте - только для выставления рейтингов, добавление в папку делает сама программа.
403 значит запрещено, возможно что-то не так с конфигами, то есть неавторизованы.
Можете привести кусок файла ratings.json?

**Comment by extempl** [comment]
Скипает - в смысле в итоговом результате все фильмы в skipped и ни одного в success/error, правильно?

**Comment by extempl** [comment]
@M9SO обновил букмарклет, кажется, там работала только первая страница. Попробуйте сейчас (нужно обновить у себя букмарклет новым кодом).
Тем не менее, в консоли должны были быть хоть какие-то ошибки (не особо читабельные, но должны были быть).

**Comment by M9SO** [comment]
Если я Вас верно понял букмарклет это та ссылка которую надо в адресную строку вставлять, её обновил, но всё тоже, скрин не знаю как дать, не разбираюсь в данной теме.

> Скипает - в смысле в итоговом результате все фильмы в skipped и ни одного в success/error, правильно?

Всё именно так.

> @M9SO обновил букмарклет, кажется, там работала только первая страница. Попробуйте сейчас (нужно обновить у себя букмарклет новым кодом).
> Тем не менее, в консоли должны были быть хоть какие-то ошибки (не особо читабельные, но должны были быть).

Именно нечего вообще.

**Comment by M9SO** [comment]
Привожу кусок файла в пример -  {"tt3749900":9,"tt2575988":9}  
Собственно это весь он, я ради теста 2 фильма пытаюсь перенести.

**Comment by extempl** [comment]
Эти фильмы есть в списке на странице которого вы запускаете импорт рейтингов?

**Comment by M9SO** [comment]
Нет, они не отмечены вообще у меня негде.

**Comment by M9SO** [comment]
Может ли это быть из за того что делаю в браузере хром?

**Comment by extempl** [comment]
> Нет, они не отмечены вообще у меня негде.

В этом и проблема. 
Смысл в том, чтобы сначала сформировать список "просмотрено", где будут все те фильмы с оценками. Потом открыть этот самый список и запустить скрипт по импорту рейтинга. Соответственно, список "просмотрено" и список с рейтингами должны совпадать.

С хромом всё должно быть в порядке.

Если фильмы (не рейтинг) не импортируются в этот самый список - надо перепроверить настройки, может некоторые значения (если вы переавторизовывались на сайте, например) нужно обновить.

**Comment by M9SO** [comment]
Да понял, изначально неверно понял как это работает, сам список просмотренного формироваться должен, но из за ошибки 403 не выходит, я всё верно понял?

**Comment by extempl** [comment]
Можно, но он создаётся приложением. То есть приложение работает, создаёт и импортирует список прямо на сайт. Параллельно генерирует `ratings.json` для дальнейшего импорта рейтингов (проще сделать пока не получилось). То есть по результату работы программы у вас уже должен был бы заполниться соответствующий список (предварительно нужно создать пустой список на сайте и посмотреть у него id, который затем устанавливается в программе).

UPD: 
> список просмотренного формироваться должен, но из за ошибки 403 не выходит

Да, вроде того. Попробуйте заново установить все параметры по руководству и попробуйте ещё раз.

**Comment by extempl** [comment]
Может быть и такое, что изменилось что-то со стороны сайта, что используемый нами способ уже не работает. Я проверю это завтра, если у вас ничего не решится.

**Comment by M9SO** [comment]
Сделал всё заново, теперь собственно выдаёт и предыдущую ошибку и новую, не знаю даже что мог сделать не так. Спасибо за развёрнутый ответ, попробую ещё завтра.
Matching movie not found
Can't change movie rating, IMDB ID is not set
Can't add movie to watchlist, IMDB ID is not set
Это всё те же 2 фильма, что и  в прошлый раз. Файл с кинопоиска не менял.

**Comment by extempl** [comment]
Это на том же списке что и перед этим? В данном случае программа, собственно, не может найти этот фильм. Такое бывает, на больших выборках (а именно для них программа и создавалась) неизбежно будет процент фильмов, которые не были импортированы.
Вполне вероятно, что ваш тестовый фильм попал в этот процент. Для тестирования попробуйте взять какой-нибудь популярный фильм и легконаходимый, Начало, например. Или сразу кидайте в программу большой список, на сайте можно будет его удалить и начать заново, если что.

**Comment by extempl** [comment]
А скиньте именно файл с кинопоиска - я попробую отследить проблему.

**Comment by M9SO** [comment]
После включения "OMDB API key:" на те же фильмы ошибка с "Can't change movie rating, IMDB ID is not set" поменялась обратно на "Can't add movie to watchlist, error status code: 403". Список тот же. Побольше список гляну завтра

**Comment by M9SO** [comment]
Вот собственно сам файл.


[kinopoisk.ru-mm (1).zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/3154134/kinopoisk.ru-mm.1.zip)

**Comment by extempl** [comment]
@M9SO Уточните, что у вас используются разные значения для полей id и sid, а так же что они достаточной длины (в конце должно быть `%0D%0A`)

**Comment by extempl** [comment]
Чуть позже по наличию времени постараюсь сделать автоматическую установку всех настроек (#33), поскольку они расширились и проще допустить ошибку (собственно, я сам её допустил и недоумевал, почему не работает).

**Comment by M9SO** [comment]
> @M9SO Уточните, что у вас используются разные значения для полей id и sid, а так же что они достаточной длины (в конце должно быть `%0D%0A`)

285 символов, значения разные, но заканчиваются на %0D%0A, id и sid.

**Comment by extempl** [comment]
В общем, я тоже сначала словил 403, но после уточнения параметров (по ошибке скопировал одно в два поля) оба фильма импортировались без проблем.

**Comment by extempl** [comment]
@M9SO пробуйте последнюю версию, там добавлена возможность добавления всех настроек одной строкой. Обратите внимание на обновления в Readme.

**Comment by M9SO** [comment]
@extempl помогло когда взял cURL, хотя после этого ещё несколько раз копировал id и sid, вручную так и не вышло, сколько не пытался. Спасибо Вам за помощь!

**Comment by extempl** [comment]
Супер. Ну там нужно все данные обновлять, не только id/sid. 
А с рейтингами пробовали теперь в списке в котором есть фильмы?

**Comment by M9SO** [comment]
Да всё нормально, обновлял все, походу у меня не то было в поле "Пара ключей-значения в текстовом запросе", так как проверил после заполнения через cURL.
