### ISSUE TITLE
ratings.json

### ISSUE THREAD

**Issue by whoizit** [REDNBLACK/J-Kinopoisk2IMDB#35]
киньте кто нибудь файл ratings.json, у меня эта прога не работает, я по быриньку скрипт накидаю для генерации этого файла.

**Comment by extempl** [comment]
Формат довольно простой, но есть нюанс - Это **только** рейтинг. И для работы импорта нужно чтоб все фильмы уже были в списке.
```
{"tt3749900":9,"tt2575988":9}
```
