### ISSUE TITLE
скрипт не работает

### ISSUE THREAD

**Issue by whoizit** [REDNBLACK/J-Kinopoisk2IMDB#36]
firefox 67.0.2
chromium 75.0.3770.90

и в адресной строке прописывал
javascript:https://github.com/REDNBLACK/J-Kinopoisk2IMDB/blob/master/core/ratingBookmarklet.min.js.txt
javascript:https://github.com/REDNBLACK/J-Kinopoisk2IMDB/raw/master/core/ratingBookmarklet.min.js.txt

и вставлял содержимое этого файла в адресную строку
и вставлял это в JS console через f12

ничего не происходит. В FF оно даже запускаться не хочет, а в chromium оно запускается с ошибкой:`
VM282:1 Uncaught SyntaxError: Unexpected token class`

**Comment by whoizit** [comment]
заработало когда скопировал содержимое этого файла и вставил в JS консоль в chromium https://github.com/REDNBLACK/J-Kinopoisk2IMDB/blob/master/core/ratingBookmarklet.js

**Comment by extempl** [comment]
Да, там есть нюанс, сейчас браузеры во избежание всяких проблем с секьюрностью стали вычищать `javascript:` при вставке строки в адресную строку, потому нужно дописывать вручную, что я указывал в ридми. А вставлять нужно было именно содержимое, по пути к файлу браузер не умеет. Вариант с консолью тоже рабочий, конечно.
