### ISSUE TITLE
Не работает HTTP error fetching URL Can't change movie rating, IMDB ID is not set Can't add movie to watchlist, IMDB ID is not set

### ISSUE THREAD

**Issue by alexeyboo** [REDNBLACK/J-Kinopoisk2IMDB#37]
[K2IDB.log](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/3596016/K2IDB.log)

Jack(1996):
HTTP error fetching URL
Can't change movie rating, IMDB ID is not set
Can't add movie to watchlist, IMDB ID is not set
и так на каждый

**Comment by extempl** [comment]
IMDB что-то поломал у себя. Гляну сегодня-завтра

**Comment by extempl** [comment]
@alexeyboo с OMDB API пробовали?

**Comment by alexeyboo** [comment]
@extempl да. И с ним, и без

**Comment by extempl** [comment]
@alexeyboo И как результат? В логах, понятное дело, будут ошибки. Но с OMDB выход успешного импорта должен быть заметно выше.
С IMDB не всё так просто, скорее всего поддержку импорта придётся чуть менее чем полностью выпилить, как устаревшую. 
Что касается рейтинга - он в принципе на данный момент не импортируется. Доступен в полуавтоматическом режиме через браузерный апплет.

**Comment by alexeyboo** [comment]
@extempl ни в какую. Настройки авторизации еще раз проверил, все правильно. Делал добавить в список с рейтингом, просто добавить в список, повышал timout до 100к, отдельно OMDB API (его я активировал), вместе с IMDB XML, Наверное все же что-то с авторизацией и куками они поменяли

**Comment by extempl** [comment]
@alexeyboo https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v1.2.7
