### ISSUE TITLE
Не запускается на windows 10 1903

### ISSUE THREAD

**Issue by alexeyboo** [REDNBLACK/J-Kinopoisk2IMDB#38]
версия 1.2.7 не запускается на windows 10 1903

**Comment by extempl** [comment]
@alexeyboo там надо файл конфигов удалить

**Comment by alexeyboo** [comment]
@extempl спасибо, в список добавилось. а можно поподробнее про браузерный апплет для рейтинга?

**Comment by extempl** [comment]
Так, браузерный апплет. Вот небольшой скринкаст: https://dsh.re/9322e
