### ISSUE TITLE
Не запускается скрипт импорта рейтингов

### ISSUE THREAD

**Issue by dgolobor** [REDNBLACK/J-Kinopoisk2IMDB#39]
Добавил в букмарки url таким образом: javascript:https://github.com/REDNBLACK/J-Kinopoisk2IMDB/blob/master/core/ratingBookmarklet.min.js.txt

При вызове ничего не происходит, ошибка в консоли chrome Uncaught SyntaxError: Unexpected end of input

**Comment by extempl** [comment]
@dgolobor https://dsh.re/9322e
