### ISSUE TITLE
Программа не работает

### ISSUE THREAD

**Issue by mi-abr** [REDNBLACK/J-Kinopoisk2IMDB#40]
Все действия выполнены по инструкции, результат такой:

<img width="309" alt="Screenshot_1" src="https://user-images.githubusercontent.com/59112845/71432274-36207e00-26fa-11ea-9a2a-918a82a86f2c.png">

**Comment by extempl** [comment]
@mi-abr Ну вы же понимаете, что такой репорт сложно чинить? Приложите, хотя-бы сэмплы файлов, которые использовали и логи из папки с программой. Видимо в ваших файлах не было найдено ни одного фильма (записи битые, или ещё что-то)

**Comment by mi-abr** [comment]
Сэмпл xls прикладываю, но лог в папке с программой (K2IDB.log) - пустой 0 кб.

[1.zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/4000745/1.zip)

**Comment by extempl** [comment]
Формат у вас странный. Слишком правильный. 
Кинопоиск экспортирует HTML разметку в XLS. Только что проверил - ничего не поменялось.
Используете этот экспорт: https://dsh.re/7896e?

**Comment by extempl** [comment]
Или похоже, что вы пересохранили файл из экселя. Так работать не будет

**Comment by bulletproof2k** [comment]
Здравствуйте, у меня ошибку выдает. 
![Ошибка К2IMDb](https://user-images.githubusercontent.com/1818579/71681201-1b56a500-2d9d-11ea-8225-06fcfe8039c0.jpg)

**Comment by extempl** [comment]
@bulletproof2k вы авторизационные данные не ввели. Смотрите тут: https://github.com/REDNBLACK/J-Kinopoisk2IMDB#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-imdb

**Comment by bulletproof2k** [comment]
Какие авторизационнные данные вы имеете в виду, все поля заполнены? Я не программист объясните доступней.

**Comment by extempl** [comment]
@bulletproof2k Попробуйте пойти путём "Генерации из cURL". 
По ссылке выше есть описание с картинками. К сожалению, невозможно вытянуть все эти данные программой, иначе так бы и сделали, так что тут деваться некуда.

**Comment by extempl** [comment]
@bulletproof2k Не знаю, какие поля у вас заполнены, на скриншоте в большом поле нет ничего (cURL), ниже есть кнопка-спойлер "установить вручную". Там что-нибудь введено в поля? Если нет, значит ничего не заполнено. Смотрите инструкции, они достаточно подробные. Если возникнут конкретные вопросы - спрашивайте. На неконкретные отвечать сложно.

**Comment by bulletproof2k** [comment]
> @ bulletproof2k Попробуйте пойти путём "Генерации из cURL".
> По ссылке выше есть описание с картинками. К сожалению, это невозможно, деваться некуда.

Нужен url списка? Как в хроме открыть консоль разработчика?

**Comment by extempl** [comment]
@bulletproof2k https://dsh.re/1791c (Developer Tools  в самом низу. Не знаю, как оно в русской локализации)
Нужен ID списка. И нужна пачка авторизационных данных.
Ещё раз загляните по ссылке: https://github.com/REDNBLACK/J-Kinopoisk2IMDB#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8-imdb

**Comment by bulletproof2k** [comment]
Вот что у меня в консоли разработчика. 
![Безымянный](https://user-images.githubusercontent.com/1818579/71735926-cc724380-2e60-11ea-9aaa-8588b76058a5.jpg)

**Comment by extempl** [comment]
@bulletproof2k 
Ага, изменились запросы. Ищите вместо `add` `tt0118767`. Рядом с ним должно быть `PUT`: https://dsh.re/b274b. Пробуйте на нём. Возможно не сработает, это я постараюсь проверить позже. Но по идее должно.

**Comment by extempl** [comment]
@bulletproof2k Извините, сам уже забыл о чём речь. 
Нужно добавить не в watchlist, а именно в список. 
В инструкции это, кстати, явно указано:
```
Далее добавляем фильм вручную в любой список (кроме watchlist)
```
Навести на иконку добавления в watchlist - откроются пользовательские списки: 
![](https://dsh.re/921cb4)
При клике на любой из них будет нужный запрос (add).

Для добавления в watchlist там да, другой запрос с другими правилами.

**Comment by extempl** [comment]
@mi-abr, @bulletproof2k всё получилось у вас?

**Comment by bulletproof2k** [comment]
Приветствую, еще не занимался.
