### ISSUE TITLE
Программа не выставляет рейтинг.

### ISSUE THREAD

**Issue by KirillK190** [REDNBLACK/J-Kinopoisk2IMDB#41]
Фильмы добавляются в список, но рейтинги совсем не выставляются. Делал всё по инструкциям.

**Comment by extempl** [comment]
@KirillK190 https://github.com/REDNBLACK/J-Kinopoisk2IMDB#%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82-%D1%80%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%D0%B0 читали?

**Comment by KirillK190** [comment]
Да, читал, но на маке нет такого файла, который описывается в инструкции

**Comment by extempl** [comment]
@KirillK190 нужно было отметить выставления рейтинга при импорте фильмов - тогда файл генерируется. Можете запустить только выставление рейтинга отдельно

**Comment by KirillK190** [comment]
Понял, спасибо.

**Comment by extempl** [comment]
Там по умолчанию выбран комбинированный режим. 
Видимо, вы выбрали только импорт фильмов. Постараюсь сделать понятнее.
