### ISSUE TITLE
Функция экспорта оценок/cписков убрана с сайта

### ISSUE THREAD

**Issue by eyenalxai** [REDNBLACK/J-Kinopoisk2IMDB#42]
Ответ от службы поддержки:

_На данный момент, увы, эта возможность была убрана с сервиса._

_Сейчас мы собираем пожелания на странице_ https://kinopoisk.userecho.com .
_Здесь можно поделиться своими идеями или проголосовать за чужие – самые популярные постараемся воплотить._

_Будем признательны, если вы проголосуете за похожее пожелание:_ https://kinopoisk.userecho.com/communities/4/topics/1326-vernite-pozhalujsta-eksport-otsenok-v-profile-udobno-sohranyat-na-kompyutere-konvertirovat-v-pdf .

**Comment by extempl** [comment]
Надеюсь что потому что хотят сделать нормальную выгрузку, потому что формат там был очень странный.

**Comment by kpspu** [comment]
Вряд ли будет хоть какая-то выгрузка от нового Кинопоиска. Для импорта фильмов теперь надо использовать возможность загрузить оценки и списки на Кинориум, далее выгрузить .csv оттуда. Форматы файлов еще не сличал.

**Comment by extempl** [comment]
Саппорт КиноПоиска 2 месяца назад
Мы отказались от этой функциональности, так как в масштабах КиноПоиска ей действительно мало пользовались. 

Но нам, конечно, не хотелось бы лишать пользователей возможности решать возникшие задачи прямо в сервисе.



Давайте по пунктам разберем задачи, для которых использовался экспорт в Excel, основываясь на комментариях топика:

1. Бэкап данных на случай удаления, закрытия сайта или других непредвиденных обстоятельств.

Мы не планируем закрывать Кинопоиск и удалять данные. 

В случае, если вы непреднамеренно удалите какие-то данные, то можете обратиться в поддержку. А если с сайтом что-то случится (хотя мы этого не допустим), мы реализуем возможность получить данные с сайта.

2. Ведение личных коллекций в xls. 

Мы делаем Кинопоиск для наших пользователей и хотели бы, чтобы вам было удобно собирать и вести свои коллекции у нас, не прибегая к дополнительным инструментам.

Нам бы хотелось услышать ваши пожелания, чего вам не хватает для этого на Кинопоиске - и мы поработаем над такой функциональностью.

3. Офлайн-режим. 

Про этот пункт не очень понятно. В наше время офлайн - это невозможность посмотреть онлайн или скачать кино и купить билеты, поэтому это выглядит самой малоиспользуемой возможностью



Мы ждем ваши отклики и пожелания по пункту 2. Ведение личных коллекций в xls и постараемся сделать Кинопоиск удобнее для вас!
