### ISSUE TITLE
Изменились куки на IMDB

### ISSUE THREAD

**Issue by kpspu** [REDNBLACK/J-Kinopoisk2IMDB#44]
Более нет id и sid.
Но даже если их подставить вручную из token, программа выдает "импортировано все 0 фильмов без ошибок". Форматы файла пробовал и как на кинопоиске, и как на imdb

**Comment by extempl** [comment]
https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v1.2.8
