### ISSUE TITLE
Проблемы с аутентификацией 

### ISSUE THREAD

**Issue by FastGrandmother** [REDNBLACK/J-Kinopoisk2IMDB#49]
При аутентификацией в ручном методе возникает ошибка "auth string (control key) lenght is less than or equal to 2!", но в at-main, session-id и ubid-main не должно быть два символа, а других полей для заполнения нет.
А при генерации из cURL валится ошибка "auth string (at-main) lenght is less than or equal to 10!"
Просьба помочь с решением проблемы.
win10 2004, java v8 update 261
![изображение](https://user-images.githubusercontent.com/39724493/90976002-d44b3900-e552-11ea-995c-ea46d7314b48.png)

**Comment by extempl** [comment]
https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v1.2.9
