### ISSUE TITLE
ошибка auth string (at-main) length is less than or equal to 10

### ISSUE THREAD

**Issue by Aleks13Y** [REDNBLACK/J-Kinopoisk2IMDB#50]
ошибка auth string (at-main) length is less than or equal to 10 
версия 1.2.9
id хз откуда брать взял uu
![12344](https://user-images.githubusercontent.com/71740515/93953298-bfc9ae80-fd53-11ea-8b9d-4e2c6993b796.png)
[kinopoisk.zip](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/files/5264953/kinopoisk.zip)

**Comment by extempl** [comment]
Посмотрите пожалуйста Readme. Вроде убрал лишнее чтоб было проще и не нужно было искать все эти переменные, но что-то не сработало 😄 

https://github.com/REDNBLACK/J-Kinopoisk2IMDB#%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8%D0%B7-curl

https://github.com/REDNBLACK/J-Kinopoisk2IMDB/blob/master/docs/ObtainIMDBcURL.png

**Comment by Aleks13Y** [comment]
я не понимаю как добавить фильм не в watchlist (Далее добавляем фильм вручную в любой список (кроме watchlist))
могу добавить только так Your Lists - (созданный ранее лист под любым названием например у меня Movie) - (3 точки ...) - Edit - Add a movie or TV show to this list: (тут вводишь любой фильм клацаеш и он в листе) при этом add параметра нету

**Comment by extempl** [comment]
@Aleks13Y при наведении на флажок: https://dsh.re/073f2

**Comment by Aleks13Y** [comment]
когда я жму на + у меня нет списка созданных листов, у меня просто добавляет в watchlist (раскрывающегося меню нету)
при наведении на флажок только click to add to watchlist
![1234](https://user-images.githubusercontent.com/71740515/94008631-fdf2bc80-fdab-11ea-8b31-3e7fa80eeaa8.png)
![321](https://user-images.githubusercontent.com/71740515/94008653-064af780-fdac-11ea-9aec-d9b1022d8937.png)

**Comment by extempl** [comment]
@Aleks13Y список появляется при наведении

**Comment by Aleks13Y** [comment]
Contributors  Show reference view with full cast and crew (advanced view) (убрал галочку с настройки в профиле появились листы)
потом не видел параметра add потому что тип данных в Network стоял other а не all. ели ели.
