### ISSUE TITLE
Добавить счётчик оставшегося времени

### ISSUE THREAD

**Issue by f242** [REDNBLACK/J-Kinopoisk2IMDB#6]
очень нехватает при большом количестве оценок

**Comment by REDNBLACK** [comment]
Да, неплохо было бы иметь. Возможно сделаю в ближайшем релизе.

**Comment by seyfer** [comment]
@REDNBLACK pull requestы принимаются?

**Comment by REDNBLACK** [comment]
@seyfer конечно! можете даже продолжить этот проект как collaborator, у меня совсем нет на него времени и интереса.

**Comment by extempl** [comment]
Done. [v1.2.5](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/releases/tag/v1.2.5)
